### ISSUE TITLE
Drop INI file format in favor of YAML

### ISSUE THREAD

**Issue by SchnWalter** [Sixdsn/terra-terminal#83]
At the moment we need to base64 encode the select_by_word setting in the settings file.

```
        if option == 'select_by_word':
            return b64decode(value)
```

I would like to suggest switching to YAML in the future for storing the user settings.

This will allow us to have nested settings in the future and remove the base64 encoding.

For example we could have a session manager that store the state of windows, tabs, and layouts.  And we could load them directly no need for code like:

```
        for section in ConfigManager.get_sections():
            if section.find('layout-screen-') != 0:
                continue

            if ConfigManager.get_conf(section, 'enabled'):
                TerraHandler.Wins.create_app(section)
```

We could have something like:

```
        for screen in ConfigManager.screens:
            if not screen['disabled']:
                TerraHandler.windows.create_app(screen)
```

**Comment by SchnWalter** [comment]
And we could also have these:

```
[layout-screen-0]
hide-tab-bar = False
hide-tab-bar-fullscreen = False
vertical-position = 150
horizontal-position = 150
width = 1280
height = 1024
fullscreen = False
disabled = False

[layout-Tabs-0-0]
name = Terminal 1
disabled = False

[layout-Child-0-0-0]
id = 0
parent = 0
axis = v
pos = -1
prog = /bin/bash
pwd = /home/user
```

Like:

```
screens:
  - hide-tab-bar: False
    hide-tab-bar-fullscreen: False
    vertical-position: 150
    horizontal-position: 150
    width: 1280
    height: 1024
    fullscreen: False
    disabled: False
    tabs:
      - name: Terminal 1
        disabled: False
        child-0:
          id: 0
          parent: 0
          axis: v
          pos: -1
          prog: /bin/bash
          pwd: /home/user
```

Or something similar.
